microservice-chart:
  namespace: "qi"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-observability-bdi
    tag: "0.8.16"
    pullPolicy: Always
  #  https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  ports:
    - 80 #http
    - 12345 #jmx-exporter
  service:
    create: true
    type: ClusterIP
    ports:
      - 80 #http
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weuuat.qi.internal.uat.platform.pagopa.it"
    path: /pagopa-qi-observabilty-bdi-service/(.*)
    servicePort: 80
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "400Mi"
      cpu: "0.40"
    limits:
      memory: "512Mi"
      cpu: "0.50"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    ENVIRONMENT: "uat"
    WEBSITE_SITE_NAME: "pagopaobservabilitybdi"
    FUNCTIONS_WORKER_RUNTIME: "java"
    ADX_CLUSTER_URL: "https://pagopaudataexplorer.westeurope.kusto.windows.net"
    ADX_DATABASE_NAME: "re"
    ADX_SOURCE_TABLE: "ReEvent"
    ADX_PERF_TABLE: "BDI_PERF_KPI"
    APP_INSIGHTS_API_URL: "https://api.applicationinsights.io/v1/apps/58b37248-3089-47ba-aa07-a2844fabe46a/query"
    APP_INSIGHTS_APP_ID: "58b37248-3089-47ba-aa07-a2844fabe46a"
    EVENT_HUB_NAME: "bdi-kpi-ingestion-dl"
    EVENT_HUB_NAMESPACE: "pagopa-u-itn-qi-evh.servicebus.windows.net"
    EVENT_HUB_KEY_NAME: "bdi-kpi-ingestion-dl-evt-tx"
    CLOUD_ROLE_NAME: "pagopa-u-apim West Europe"
    BETTERSTACK_API_URL: "https://uptime.betterstack.com/api/v2/monitors/2789316/sla"
    PERF-03_OPERATION_NAME: "u-node-for-psp-api-auth;rev=1 - 63756cf1451c1c01c4186bab" # sendPaymentOutcomeV2
    PERF-04_OPERATION_NAME: "u-node-for-psp-api-auth;rev=1 - 63fcb0f539519a2c40fd431a" # nodoInviaFlussoRendicontazione
    PERF-05_OPERATION_NAME: "u-nodo-per-pa-api-auth;rev=1 - 636cb7e9451c1c01c4186998" # nodoChiediElencoFlussiRendicontazione
    PERF-06_OPERATION_NAME: "u-nodo-per-pa-api-auth;rev=1 - 636cb7e9451c1c01c4186999" # nodoChiediFlussoRendicontazione
    AZURE_AD_TENANT_ID: "7788edaf-0346-4068-9d79-c868aed15b3d"
    AZURE_AD_CLIENT_ID: "74ae19a9-1309-4751-888e-48f85935622e"
    AZURE_AD_AI_TENANT_ID: "7788edaf-0346-4068-9d79-c868aed15b3d"
    AZURE_AD_AI_CLIENT_ID: "19324b8f-0bdf-4036-bf15-2cd501f363c0"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-u-connection-string"
    AZURE_AD_CLIENT_SECRET: "azure-ad-client-secret"
    APP_INSIGHTS_API_KEY: "bdi-ai-api-key"
    EVENT_HUB_KEY: "evh-tx-bdi-kpi-key"
    BETTERSTACK_API_KEY: "betterstack-api-key"
    AZURE_AD_AI_CLIENT_SECRET: "azure-ad-ai-client-secret"
  keyvault:
    name: "pagopa-u-qi-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  canaryDelivery:
    create: false
