microservice-chart:
  namespace: "qi"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-observability-bdi
    tag: "0.8.18-4-fix-deploy-wli-helm7"
    pullPolicy: Always
  #  https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  ports:
    - 8080 #http
    - 12345 #jmx-exporter
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080 #http
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weudev.qi.internal.dev.platform.pagopa.it"
    path: /pagopa-qi-observabilty-bdi-service/(.*)
    servicePort: 8080
  serviceAccount:
    name: "qi-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "400Mi"
      cpu: "0.40"
    limits:
      memory: "512Mi"
      cpu: "0.50"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    ENVIRONMENT: "dev"
    WEBSITE_SITE_NAME: "pagopaobservabilitybdi"
    FUNCTIONS_WORKER_RUNTIME: "java"
    ADX_CLUSTER_URL: "https://pagopaddataexplorer.westeurope.kusto.windows.net"
    ADX_DATABASE_NAME: "re"
    ADX_SOURCE_TABLE: "ReEvent"
    ADX_PERF_TABLE: "BDI_PERF_KPI"
    APP_INSIGHTS_API_URL: "https://api.applicationinsights.io/v1/apps/76537955-6128-45d4-bf32-b0034ed17e4d/query"
    APP_INSIGHTS_APP_ID: "76537955-6128-45d4-bf32-b0034ed17e4d"
    EVENT_HUB_NAME: "bdi-kpi-ingestion-dl"
    EVENT_HUB_NAMESPACE: "pagopa-d-itn-qi-evh.servicebus.windows.net"
    EVENT_HUB_KEY_NAME: "bdi-kpi-ingestion-dl-evt-tx"
    CLOUD_ROLE_NAME: "pagopa-d-apim West Europe"
    BETTERSTACK_API_URL: "https://uptime.betterstack.com/api/v2/monitors/2789316/sla"
    PERF-03_OPERATION_NAME: "d-node-for-psp-api-auth;rev=1 - 637608a0c257810fc0ecfe22" # sendPaymentOutcomeV2
    PERF-04_OPERATION_NAME: "d-nodo-per-psp-api-auth;rev=1 - 63fc7fce3b3a670f709d79e9" # nodoInviaFlussoRendicontazione
    PERF-05_OPERATION_NAME: "d-nodo-per-pa-api-auth;rev=1 - 6352c3bcc257810f183b398b" # nodoChiediElencoFlussiRendicontazione
    PERF-06_OPERATION_NAME: "d-nodo-per-pa-api-auth;rev=1 - 6352c3bcc257810f183b398c" # nodoChiediFlussoRendicontazione
    AZURE_AD_TENANT_ID: "7788edaf-0346-4068-9d79-c868aed15b3d"
    AZURE_AD_CLIENT_ID: "8677a3ca-8d05-453f-947c-0bdb1d15e512"
    AZURE_AD_AI_TENANT_ID: "7788edaf-0346-4068-9d79-c868aed15b3d"
    AZURE_AD_AI_CLIENT_ID: "cd5c171b-324f-4ccf-ada5-895a7b2d4fb8"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-d-connection-string"
    AZURE_AD_CLIENT_SECRET: "azure-ad-client-secret"
    APP_INSIGHTS_API_KEY: "bdi-ai-api-key"
    EVENT_HUB_KEY: "evh-tx-bdi-kpi-key"
    BETTERSTACK_API_KEY: "betterstack-api-key"
    AZURE_AD_AI_CLIENT_SECRET: "azure-ad-ai-client-secret"
  keyvault:
    name: "pagopa-d-qi-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  canaryDelivery:
    create: false
