microservice-chart:
  namespace: "<namespace>" # TODO
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopadcommonacr.azurecr.io/pagopa<project-name>  # TODO
    tag: "0.0.1"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 80
  ingress:
    create: true
    host: "weudev.<namespace>.internal.dev.platform.pagopa.it"  # TODO
    path: /pagopa-<project-name>-service/(.*) # TODO
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.25"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: "pagopa<project-name>" # required to show cloud role name in application insights # TODO
    FUNCTIONS_WORKER_RUNTIME: "java"
    ENVIRONMENT: "local"
    KEYVAULT_URI: "https://pagopa-d-observ-kv.vault.azure.net/"
    ADX_CLUSTER_URL: "https://pagopaddataexplorer.westeurope.kusto.windows.net"
    ADX_DATABASE_NAME: "re"
    ADX_SOURCE_TABLE: "ReEvent"
    ADX_PERF_TABLE: "BDI_PERF_KPI"
    PERF_DATA_TIMER_TRIGGER: "0 0 2 5 * *"
    PERF_02E_TIMER_TRIGGER: "0 0 * * * *"
    AAI_API_URL: "https://api.applicationinsights.io/v1/apps/76537955-6128-45d4-bf32-b0034ed17e4d/query"
    CLOUD_ROLE_NAME: "pagopa-d-apim West Europe"
    PERF-03_OPERATION_NAME: "d-node-for-psp-api;rev=1 - 637601f8c257810fc0ecfe07"
    PERF-04_OPERATION_NAME: "d-nodo-per-psp-api;rev=1 - 61e9630cb78e981290d7c74c" 
    PERF-05_OPERATION_NAME: "d-nodo-per-pa-api;rev=1 - 6218976195aa0303ccfcf901" 
    PERF-06_OPERATION_NAME: "d-node-for-psp-api;rev=1 - 637601f8c257810fc0ecfe07" 
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string' # TODO set in kv
  keyvault:
    name: "pagopa-d-<namespace>-kv" # TODO
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
