name: Collect BDI KPI Data
on:
  schedule:
    - cron: '0 1 * * *'
    
  workflow_dispatch:
    inputs:
      start_date:
        required: false
        type: string
        description: Set start date (Pattern "yyyy-mm-ddThh:mm:ss"  default N/A)
        default: "N/A"

      end_date:
        required: false
        type: string
        description: Set start date (Pattern "yyyy-mm-ddThh:mm:ss"  default N/A)
        default: "N/A"

      kpi_id:
        required: false
        type: choice
        description: select kpi
        options:
          - ALL
          - PERF-01
          - PERF-02
          - PERF-02E
          - PERF-03
          - PERF-04
          - PERF-05
          - PERF-06
        default: ALL

      notify:
        description: 'notify report results'
        required: false
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  
  collect_data_script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: '3.12'

      - name: Checkout
        id: checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: Install dependencies
        run: |
          pip install -r ./python/collect-bdi-kpi/requirements.txt

      - name: Run Collect Perf Data
        shell: bash
        env:
          API_KEY: ${{ secrets.BDI_API_KEY }}
          API_URL: "https://api.platform.pagopa.it/qi/perf-kpi-bdi/v1/perf-data"
          PYTHONUNBUFFERED: "1"
          START_DATE_INPUT: ${{ inputs.start_date || 'N/A' }}
          END_DATE_INPUT: ${{ inputs.end_date || 'N/A' }}
          KPI_ID_INPUT: ${{ inputs.kpi_id || 'ALL' }}

        run: |          
          cd ./python/collect-bdi-kpi

          START_DATE="$START_DATE_INPUT"
          END_DATE="$END_DATE_INPUT"
          KPI_ID="$KPI_ID_INPUT"

          echo "Running collect-perf-data.py with params:"
          echo "kpi_id: $KPI_ID"
          echo "start_date: $START_DATE"
          echo "end_date: $END_DATE"

          python collect-perf-data.py --kpi_id "$KPI_ID" --start_date "$START_DATE" --end_date "$END_DATE"

      - name: Send notification to Slack
        id: slack
        if: ${{ (github.event_name == 'workflow_dispatch' && inputs.notify != 'false') || (github.event_name == 'schedule' && true) }}
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 #v1.24.0
        with:
          payload-file-path: "./python/collect-bdi-kpi/payload.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
